type Mutation {
  """
  Create or update one or more climbs.
  """
  updateClimbs(input: UpdateClimbsInput): [ID]

  """
  Delete one or more climbs
  """
  deleteClimbs(input: DeleteManyClimbsInput): Int
}

input DeleteManyClimbsInput {
  parentId: ID
  idList: [ID]
}

"""
Create/update climbs input parameter.
"""
input UpdateClimbsInput {
  "Parent area ID"
  parentId: ID!
  "Array of change records"
  changes: [SingleClimbChangeInput]
}

"""
Climb change record.  If the climb ID is omitted or does not exist in the database, a new climb will be created.
"""
input SingleClimbChangeInput {
  "Climb UUID"
  id: ID
  name: String
  disciplines: DisciplineType
  grade: String
  leftRightIndex: Int
  description: String
  location: String
  protection: String
  "Legacy FA data"
  fa: String
  "Length in meters"
  length: Int
}

input DisciplineType {
  "https://en.wikipedia.org/wiki/Traditional_climbing"
  trad: Boolean
  "https://en.wikipedia.org/wiki/Sport_climbing"
  sport: Boolean
  "https://en.wikipedia.org/wiki/Bouldering"
  bouldering: Boolean
  "https://en.wikipedia.org/wiki/Alpine_climbing"
  alpine: Boolean
  "https://en.wikipedia.org/wiki/Ice_climbing"
  snow: Boolean
  "https://en.wikipedia.org/wiki/Ice_climbing"
  ice: Boolean
  mixed: Boolean
  "https://en.wikipedia.org/wiki/Aid_climbing"
  aid: Boolean
  "https://en.wikipedia.org/wiki/Top_rope_climbing"
  tr: Boolean
}
