input AllHistoryFilter {
  uuidList: [ID]
  userUuid: ID
  fromDate: Date
  toDate: Date
}

input AreaHistoryFilter {
  areaId: ID
}

input OrganizationHistoryFilter {
  orgId: MUUID
}

type UpdateDescription {
  updatedFields: [String]
}

type Change {
  changeId: ID!
  dbOp: String!
  fullDocument: Document
  updateDescription: UpdateDescription
}

union Document = Area | Climb | Organization

type History {
  id: ID!
  editedBy: ID!
  editedByUser: String
  operation: String!
  createdAt: Date!
  changes: [Change]
}

type Query {
  getChangeHistory(filter: AllHistoryFilter): [History]
  getAreaHistory(filter: AreaHistoryFilter): [History]
  getOrganizationHistory(filter: OrganizationHistoryFilter): [History]
}

"""Author metadata"""
type AuthorMetadata {
  createdAt: Date!
  createdBy: ID!
  createdByUser: String
  updatedAt: Date!
  updatedBy: ID!
  updatedByUser: String
}
