type Mutation {
  setTag(input: MediaInput): TagEntryResult
}

type Mutation {
  removeTag(tagId: ID!): DeleteTagResult
}

type Query {
  getTagsByMediaIdList(uuidList: [ID]): [TagEntryResult]
}

type Query {
  getRecentTags(userLimit: Int): [MediaListByAuthorType]
}

type Query {
  """
  Get a list of users and their tagged photo count
  """
  getTagsLeaderboard(limit: Int): [TagsLeaderboardType]
}

type TagsLeaderboardType {
  userUuid: ID!
  total: Int!
}

"Core attributes of a tag"
interface ITag {
  id: ID!
  username: String
  mediaUuid: ID!
  mediaUrl: String!
  mediaType: Int!
  destination: ID!
  destType: Int!
  width: Int!
  height: Int!
  format: String!
  mtime: Date!
  birthTime: Date!
  size: Int!
}

"An area tag"
type AreaTag implements ITag {
  id: ID!
  username: String
  mediaUuid: ID!
  mediaUrl: String!
  mediaType: Int!
  destination: ID!
  destType: Int!
  width: Int!
  height: Int!
  format: String!
  mtime: Date!
  birthTime: Date!
  size: Int!
  area: Area
}

"A climb tag"
type ClimbTag implements ITag {
  id: ID!
  username: String
  mediaUuid: ID!
  mediaUrl: String!
  mediaType: Int!
  destination: ID!
  destType: Int!
  width: Int!
  height: Int!
  format: String!
  mtime: Date!
  birthTime: Date!
  size: Int!
  climb: Climb
}

union MediaTag = AreaTag | ClimbTag

type BaseTag implements ITag {
  id: ID!
  username: String
  mediaUuid: ID!
  mediaUrl: String!
  mediaType: Int!
  destination: ID!
  destType: Int!
  width: Int!
  height: Int!
  format: String!
  mtime: Date!
  birthTime: Date!
  size: Int!
}

"All tags by an author"
type MediaListByAuthorType {
  authorUuid: ID!
  tagList: [MediaTag]
}

# "A tag linking the media with a climb"
# type ClimbTag {
#   id: ID!
#   mediaUuid: ID!
#   mediaUrl: String!
#   mediaType: Int!
#   climb: Climb
#   destType: Int!
# }

# "A tag linking the media with an area"
# type AreaTag {
#   id: ID!
#   mediaUuid: ID!
#   mediaUrl: String!
#   mediaType: Int!
#   area: Area
#   destType: Int!
# }

union TagEntryResult = ClimbTag | AreaTag



"Result of a delete tag operation"
type DeleteTagResult {
  id: ID!
  mediaUuid: ID!
  destinationId: ID!
  destType: Int!
}

"Input param for creating a new tag"
input MediaInput {
  mediaUuid: ID!
  mediaUrl: String!
  mediaType: Int!
  destinationId: ID!
  destType: Int!
}
