type Mutation {
  """
  Add an organization
  """
  addOrganization(input: AddOrganizationInput): Organization

  """
  Update organization attributes
  """
  updateOrganization(input: OrganizationEditableFieldsInput): Organization
}

input AddOrganizationInput {
  displayName: String!
  orgType: String!
  associatedAreaIds: [MUUID]
  excludedAreaIds: [MUUID]
  website: String
  email: String
  donationLink: String
  instagramLink: String
  description: String
}

input OrganizationEditableFieldsInput {
  orgId: MUUID!
  associatedAreaIds: [MUUID]
  excludedAreaIds: [MUUID]
  displayName: String
  website: String
  email: String
  donationLink: String
  instagramLink: String
  description: String
}
