type Mutation {
  addPost(input: AddPostInput): AddPostResponse
}

type Mutation {
  removePost(input: RemovePostInput): RemovePostResponse
}

"Input params for creating a new post"
input AddPostInput {
  userId: ID!
  mediaIds: [ID]!
  description: String
}

type AddPostResponse {
  postId: String
}

"Input params for removing an existing post"
input RemovePostInput {
  postId: ID!
}

type RemovePostResponse {
  numDeleted: String
}
