type Mutation {
  createUser(input: NewUserInput): Boolean
  # updateUsername(input: UsernameInput): Boolean
  updateUserProfile(input: UserProfileInput): Boolean
}


type Query {
  getUsername(userUuid: ID!): UsernameInfo

}
input NewUserInput {
  userUuid: ID!
}

input UsernameInput {
  userUuid: ID!
  username: String!
}

type UsernameInfo {
   userUuid: ID!
   username: String!
}

type UserProfileInput {
  username: String
  displayName: String
}