type Mutation {
  createUser(input: NewUserInput): Boolean

  "Update a user profile.  Create a new profile if it doesn't exist."
  updateUserProfile(input: UserProfileInput): Boolean
}

type Query {
  "Get user name from user uuid"
  getUsername(userUuid: ID!): UsernameMapping

  getUserProfile(userUuid: ID!): UserProfile
}
input NewUserInput {
  userUuid: ID!
}

input UsernameInput {
  userUuid: ID!
  username: String!
}

input UserProfileInput {
  username: String
  displayName: String
}

type UserProfile {
  userUuid: ID
  usernameInfo: Username
  displayName: String
  bio: String
  website: String
}

type Username {
  username: String!
  lastUpdated: Date!
}

type UsernameMapping {
  userUuid: ID!
  username: String!
  lastUpdated: Date!
}
