type Query {
  organization(muuid: UUID): Organization
  organizations(filter: OrgFilter, sort: OrgSort, limit: Int, offset: Int): [Organization]
}

"A climbing area, wall or crag"
type Organization {
  id: ID!
  """
  Type of organization. Currently we only support local climbing organizations, which
  are associated with certain climbing areas. In future there may be advocacy groups
  like the Access Fund or interest groups like the American Alpine Club that are not
  associated with any specific climbing areas.
  """
  orgType: String!
  "We use orgId for identification of organizations. The id field is used in internal database relations."
  orgId: UUID!

  associatedAreaIds: [UUID]
  excludedAreaIds: [UUID]

  "Name of organization to be displayed on the site."
  displayName: String!
  content: OrganizationContent
  createdAt: Date
  createdBy: UUID
  updatedAt: Date
  updatedBy: UUID
}

type OrganizationContent {
  website: String
  email: String
  donationLink: String
  instagramLink: String
  facebookLink: String
  hardwareReportLink: String
  description: String
}

input OrgSort {
  displayName: Int
  updatedAt: Int
}

input OrgFilter {
  displayName: DisplayNameFilter
  associatedAreaIds: AssociatedAreaIdsFilter
  excludedAreaIds: ExcludedAreaIdsFilter
}

input DisplayNameFilter {
  match: String!
  exactMatch: Boolean
}

"Filter for organizations that are associated with an area."
input AssociatedAreaIdsFilter {
  includes: [UUID]
}

"Filter for organizations that have not excluded themselves from an area."
input ExcludedAreaIdsFilter {
  excludes: [UUID]
}
