type Mutation {
  """
  Update a user profile or create a new profile if it doesn't exist.
  Note:  The email field is required when creating a new profile and
  will be ignore in subsequent update calls to prevent users from 
  changing their email.  The frontend  calls this API whenever a new user 
  logs in; their email therefore should have been verified at this point.
  When we support email address change in the future, we will need to 
  create a separate update-email mutation to make sure users take the
  neccessary steps.
  """
  updateUserProfile(input: UserProfileInput): Boolean
}

type Query {
  user(input: LocateUserBy!): UserPublicProfile!
  userPage(input: LocateUserBy!): UserPublicPage!

  "Check to see if a username already exists in the database." usernameExists(
    input: UsernameInput!
  ): Boolean
  "Get username object by user uuid" getUsername(
    input: UserIDInput!
  ): UsernameDetail
  "Get user public profile" getUserPublicProfileByUuid(
    input: UserIDInput!
  ): UserPublicProfile
  "A users page is their profile + their media (paginated)" getUserPublicPage(
    input: UsernameInput!
  ): UserPublicPage
}

"""
Users can be principally identified either by their username or by their user id.
There is reason to prefer the latter over the former - usernames can be changed, and
in any scenario where you might be caching or trying to produce a permanent resource
reference you will want to prefer the uuid over the username.
"""
input LocateUserBy {
  username: String
  userUuid: ID
}

input UsernameInput {
  username: String!
}

input UserIDInput {
  userUuid: ID!
}

input UserProfileInput {
  userUuid: ID!
  username: String
  displayName: String
  bio: String
  website: String
  email: String
  avatar: String
}

"Username detail object" type UsernameDetail {
  userUuid: ID!
  username: String
  lastUpdated: Date
}

type UserPublicPage {
  profile: UserPublicProfile
  media: UserMedia
}

type UserPublicProfile {
  userUuid: ID!
  username: String!
  displayName: String
  bio: String
  website: String
  avatar: String
}
