version: '3.8'
services:
  mongo_opentacos:
    hostname: mongodb
    image: mongo:5
    env_file:
    - .env
    ports:
      - 27017:27017
    volumes:
      - opentacos_mongodb_data:/data/db
      - ./:/opt/keyfile/
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    entrypoint:
      - bash
      - -c
      - |
        cp /opt/keyfile/keyfile /data/db/replica.key
        chmod 400 /data/db/replica.key
        chown 999:999 /data/db/replica.key
        exec docker-entrypoint.sh $$@
    command: "mongod --bind_ip_all --replSet rs0 --keyFile /data/db/replica.key"
  mongosetup:
    image: mongo:5
    depends_on:
      - mongo_opentacos
    env_file:
      - .env
    volumes:
      - .:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]
volumes:
  opentacos_mongodb_data:
