version: '3.8'
services:
  mongo-express:
    image: mongo-express
    restart: always
    env_file:
    - .env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo_opentacos:27017/opentacos?authSource=admin&replicaSet=rs0
    depends_on:
    - mongo_opentacos
volumes:
  opentacos_mongodb_data:
