name: 'docker publish'
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 'Checkout Project'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 1

      - name: Install Dependencies and lint code
        run: yarn install && yarn lint

      - name: Test build
        run: yarn build-release

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: vnguyen/openbeta-graph-api:latest
