name: 'tests'

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: 'Checkout Project'
        uses: 'actions/checkout@v2.3.4'
        uses: 'borales/actions-yarn@v2.3.0'
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: yarn install

      - name: Lint and build
        run: yarn build
