name: 'tests'

on:
  push:
    branches:
    - develop
  pull_request:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.15'

      - name: 'Checkout Project'
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 1

      - name: Install Dependencies and lint code
        run: yarn install && yarn lint

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 5
          mongodb-replica-set: rs0

      - name: Wait for the database to start
        run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- localhost:27017 -- echo "Database is up"
        env:
          WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
      
      - name: Setup test user
        run: |
           source .env && \
           docker exec mongodb mongosh admin --eval "db.createUser({user: '${MONGO_INITDB_ROOT_USERNAME}', pwd: '${MONGO_INITDB_ROOT_PASSWORD}', roles: ['readWrite']})"

      - name: Restart mongo
        run: |
          docker container restart mongodb

      - name: Build and run tests
        run: yarn test
        env:
          NODE_OPTIONS: --experimental-vm-modules

