name: 'tests'

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'

      - name: 'Checkout Project'
        uses: 'actions/checkout@v2'
        with:
          fetch-depth: 1

      - name: Install Dependencies and lint code
        run: yarn install && yarn lint

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5
          mongodb-replica-set: rs0

      - name: Wait for the database to start
        run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- localhost:27017 -- echo "Database is up"
        env:
          WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3
      
      - name: Setup test user
        run: |
           source .env && \
           mongo admin --eval "db.createUser({user: '${MONGO_INITDB_ROOT_USERNAME}', pwd: '${MONGO_INITDB_ROOT_PASSWORD}', roles: ['readWrite']})"

      - name: Lint and test
        run: yarn test
        env:
          NODE_OPTIONS: --experimental-vm-modules

      - name: Build
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: vnguyen/openbeta-graph-api:latest
